src/objects/Epic__c.object
<CustomObject>
    <description>An Epic is a ticket that holds different related tickets</description>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Epic</label>
    <nameField>
        <displayFormat>EPIC-{0000000}</displayFormat>
        <label>Epic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ticket__c.object
<CustomObject>
    <description>Ticket is a request to build or fix functionality</description>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>Epic__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EpicTriggerHandler.cls
public class EpicTriggerHandler extends TriggerHandler {

  public override void afterUpdate() {
    Epic__c afterEpic = (Epic__c) Trigger.new[0];
    Epic__c beforeEpic = (Epic__c) Trigger.old[0];
      
    List<Ticket__c> tickets = [
        SELECT Id, Title__c
        FROM Ticket__c
        WHERE Epic__c = :afterEpic.Id
    ];
    
    for (Ticket__c ticket : tickets) {
      updateTicketTitle(ticket, afterEpic, beforeEpic);
    }
  }

  private void updateTicketTitle(Ticket__c ticket, Epic__c afterEpic, Epic__c beforeEpic) {
    // If the title of the epic changes, we need to prepend the depending tickets' titles with the new epic title.
    if (afterEpic.Title__c != beforeEpic.Title__c) {
      ticket.Title__c = '[' + afterEpic.Title__c + '] ' + ticket.Title__c;
    }
    
    update ticket;
  }
}