src/objects/Epic__c.object
<CustomObject>
    <description>An Epic is a ticket that holds different related tickets</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>PARTIALLY DONE</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Estimated_Days_of_Work__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total days of work under this epic</description>
        <label>Total Estimated Days of Work</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Epic</label>
    <nameField>
        <displayFormat>EPIC-{0000000}</displayFormat>
        <label>Epic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ticket__c.object
<CustomObject>
    <description>Ticket is a request to build or fix functionality</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Epic</label>
        <referenceTo>Epic__c</referenceTo>
        <relationshipLabel>Tickets</relationshipLabel>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Days_of_Work__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Estimated days to finish this ticket</description>
        <label>Estimated Days of Work</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NEW</fullName>
                </value>
                <value>
                    <fullName>READY</fullName>
                </value>
                <value>
                    <fullName>IN PROGRESS</fullName>
                </value>
                <value>
                    <fullName>BLOCKED</fullName>
                </value>
                <value>
                    <fullName>DONE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TicketTriggerHandler.cls
public class TicketTriggerHandler extends TriggerHandler {
  public override void afterInsert() {
    updateTotalEstimatedDaysOnEpic();
  }
    
  public override void afterUpdate() {
    updateTotalEstimatedDaysOnEpic();
  }
  
  public override void beforeInsert() {
    List<Ticket__c> newTickets = (List<Ticket__c>) Trigger.new;
    preventClosing(newTickets, null);
  }

  public override void beforeUpdate() {
    List<Ticket__c> newTickets = (List<Ticket__c>) Trigger.new;
    Map<Id, Ticket__c> oldTickects = (Map<Id, Ticket__c>) Trigger.oldMap;
    preventClosing(newTickets, oldTickects);
  }
  
  private void updateTotalEstimatedDaysonEpic() {
    List<Ticket__c> newTickets = (List<Ticket__c>) Trigger.new;
    Map<Id, Decimal> newWorkDaysByEpic = new Map<Id, Decimal>();
    for (Ticket__c ticket : newTickets) {
      newWorkDaysByEpic.put(ticket.Epic__c, ticket.Estimated_Days_of_Work__c);
    }
      
    List<Epic__c> epics = [
        SELECT Id, Total_Estimated_Days_of_Work__c
        FROM Epic__c
        WHERE ID = :newWorkDaysByEpic.keySet()
    ];
    for (Epic__c epic : epics) {
      epic.Total_Estimated_Days_of_Work__c += newWorkDaysByEpic.get(epic.Id);
    }
      
    update epics;
  }

  private void preventClosing(List<Ticket__c> newTickets, Map<Id, Ticket__c> beforeTickets) {
    List<Ticket__c> ticketsToUpdate = new List<Ticket__c>();
    for (Ticket__c ticket : newTickets) {
      if (ticket.Status__c == 'DONE' && ticket.End_Date__c == null) {
        String previousStatus = 'NEW';
        if (beforeTickets != null) {
          previousStatus = beforeTickets.get(ticket.Id).Status__c;
        }
        ticket.Status__c = previousStatus;
        ticketsToUpdate.add(ticket);
      }
    }
    update ticketsToUpdate;
  }
}